# Generated by Django 3.2 on 2023-08-26 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataEncadreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('numTel', models.CharField(max_length=15)),
                ('addEmail', models.EmailField(max_length=250)),
                ('untEnseignaement', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DataReact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=150)),
                ('quartier', models.CharField(max_length=150)),
                ('niveau', models.CharField(max_length=100)),
                ('classe', models.CharField(max_length=200)),
                ('matiere', models.CharField(max_length=300)),
                ('jours', models.CharField(max_length=300)),
                ('heure', models.CharField(max_length=100)),
                ('numTel', models.CharField(max_length=150)),
                ('addEmail', models.EmailField(max_length=250)),
                ('addresse', models.CharField(max_length=250)),
                ('taux', models.CharField(max_length=150)),
                ('Price', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'data',
            },
        ),
    ]
