# Generated by Django 4.2.2 on 2023-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_dataencadreur'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareact',
            name='addEmail',
            field=models.EmailField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datareact',
            name='addresse',
            field=models.EmailField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datareact',
            name='matiere',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datareact',
            name='numTel',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dataencadreur',
            name='addEmail',
            field=models.EmailField(max_length=250),
        ),
    ]
