# Generated by Django 4.2.2 on 2023-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_datareact_addemail_datareact_addresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datareact',
            name='addresse',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='datareact',
            name='numTel',
            field=models.CharField(max_length=150),
        ),
    ]
