# Generated by Django 4.2.2 on 2023-07-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_datareact_addresse_alter_datareact_numtel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareact',
            name='Price',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
