# Generated by Django 4.1.3 on 2023-07-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_datareact_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datareact',
            options={'verbose_name': 'data'},
        ),
        migrations.AddField(
            model_name='datareact',
            name='heure',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datareact',
            name='jours',
            field=models.CharField(default=0, max_length=300),
            preserve_default=False,
        ),
    ]
