# Generated by Django 4.1.3 on 2023-07-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_alter_datareact_options_datareact_heure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datareact',
            name='quartier',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datareact',
            name='taux',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datareact',
            name='ville',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
